### ISSUE TITLE
Add bunkers

### ISSUE THREAD

**Issue by lanahra** [lanahra/space-invaders#26]
There should be 4 bunkers that protect the player at the bottom of the screen. They are made of 5 or 6 individual blocks that take damage with each bullet hit, friend or foe.

They should be equally space at the bottom of the screen.

**Comment by arthuradolfo** [comment]
Actually, in the game referenced by Schnorr (can be accessed [here](http://www.pacxon4u.com/space-invaders/)), in the definition of project, the bunkers have 10 individual blocks (3 rows, 4 columns, doesn't have intermediate blocks only in the first bottom row)
